class ChangeGithubUserTable < ActiveRecord::Migration

  def change
    change_column :github_users, :public_repos, :integer #better to store in the db as integer...
    change_column :github_users, :followers, :integer #better to store in the db as integer...
    change_column :github_users, :following, :integer #better to store in the db as integer...
  end
end
